name: Link Checker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check Links
        uses: lycheeverse/lychee-action@v1
        with:
          # Проверяем все .md файлы
          args: --verbose --no-progress './**/*.md'
          fail: true
